import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import { GlobalContextProvider } from './Context/store'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}




export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        
      </head>
      <body>
        <GlobalContextProvider>
           {children}
        </GlobalContextProvider>
        </body>
    </html>
  )
}
